package ca.bc.gov.educ.api.gradalgorithm.constants;

/**
 * The enum Event type.
 */
public enum EventType {
  GET_ASSESSMENT_STUDENTS,
  GET_STUDENT_COURSES,
  GET_COURSE_REQUIREMENTS,
  GET_COURSE_RESTRICTIONS,
  GET_ASSESSMENT_REQUIREMENTS,
  UPDATE_SCHOOL,
  CREATE_SCHOOL,
  GET_SCHOOL,
  UPDATE_DISTRICT,
  CREATE_DISTRICT,
  UPDATE_AUTHORITY,
  CREATE_AUTHORITY,
  GET_AUTHORITY,
  GET_PAGINATED_SCHOOLS,
  GET_PAGINATED_AUTHORITIES,
  MOVE_SCHOOL,
  CREATE_SCHOOL_CONTACT,
  UPDATE_SCHOOL_CONTACT,
  DELETE_SCHOOL_CONTACT,
  CREATE_DISTRICT_CONTACT,
  UPDATE_DISTRICT_CONTACT,
  DELETE_DISTRICT_CONTACT,
  CREATE_AUTHORITY_CONTACT,
  UPDATE_AUTHORITY_CONTACT,
  DELETE_AUTHORITY_CONTACT,
  CREATE_GRAD_SCHOOL,
  UPDATE_GRAD_SCHOOL;

  public static boolean isValid(String value) {
    if (value == null) {
      return false;
    }
    try {
      EventType.valueOf(value);
      return true;
    } catch (IllegalArgumentException e) {
      return false;
    }
  }
}
