#Keycloak/OAuth properties
security:
  oauth2:
    resource:
      jwt:
        key-value: ${KEYCLOAK_PUBLIC_KEY}

#DB Properties
spring:
  jmx:
    enabled: false
  datasource:
    hikari:
      pool-name: grad-algorithm-api-cp
      maximum-pool-size: ${MAXIMUM_POOL_SIZE}
      connection-timeout: ${CONNECTION_TIMEOUT}
      max-lifetime: ${MAX_LIFETIME}
    url: ${CONNECTION_STRING}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false

#Logging properties
logging:
  file:
    max-history: 1
    clean-history-on-start: true
    max-size: 20MB
    name: /logs/app.log
  #pattern:
  #  file: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  #  console: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  level:
    ca:
      bc:
        gov:
          educ:
            api:
              gradalgorithm: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}

#Local properties
server:
  undertow:
    threads:
      worker: 128
      io: 16
  #port: ${HTTP_PORT}

#API Documentation
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs-ui.html
    operationsSorter: alpha

#Endpoint properties
endpoint:
  grad-trax-api:
    school-by-min-code:
      url: https://educ-grad-trax-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/school/%s
  grad-program-api:
    get-program-algorithm-data:
      url: https://educ-grad-program-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/program/algorithmdata?
    get-optional-program:
      url: https://educ-grad-program-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/program/optionalprograms/%s/%s
    optional_program_name_by_optional_program_id:
      url: https://educ-grad-program-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/program/optionalprograms/id/%s
  grad-course-api:
    get-course-algorithm-data:
      url: https://grad-course-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/course-algorithm/pen/%s
  grad-assessment-api:
    get-assessment-algorithm-data:
      url: https://grad-assessment-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/assessment/assessment-algorithm/pen/%s
  grad-student-graduation-api:
    get-algorithm-data:
      url: https://educ-grad-student-graduation-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/algo
    get-graduation-message:
      url: https://educ-grad-student-graduation-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/transcript/gradmessages/pgmCode/%s/msgType/%s
  grad-student-api:
    get-student-by-studentid:
      url: https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/student/stdid/%s
    get-graduation-status: 
      url: https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/student/studentid/%s/algorithm
    get-grad-student-algo-data: 
      url: https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/student/algorithmdata/%s
    get-graduation-student-record:
      get-optional-programs:
        url: https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/student/specialprogram/studentid/%s
  rule-engine-api:
    base-domain: https://rule-engine-api-77c02f-dev.apps.silver.devops.gov.bc.ca
    api-keyword: api
    version: v1
    root: rule-engine
    base-url: ${endpoint.rule-engine-api.base-domain}/${endpoint.rule-engine-api.api-keyword}/${endpoint.rule-engine-api.version}/${endpoint.rule-engine-api.root}
    endpoints:
      run-grad-algorithm-rules: run-grad-algorithm-rules